# syntax=docker/dockerfile:1
FROM balenalib/%%BALENA_MACHINE_NAME%%-ubuntu:focal
RUN apt update && apt upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt install -y ca-certificates sudo apt-utils net-tools
COPY nm-mgmt-collect-http-anon-v0.7.0-arm64-dev1.deb /
RUN dpkg -i nm-mgmt-collect-http-anon-v0.7.0-arm64-dev1.deb
COPY /collectd-http.sh /
RUN chown netrics:netrics /collectd-http.sh
RUN chmod u+x /collectd-http.sh
USER netrics
CMD ["/collectd-http.sh"] 
