# syntax=docker/dockerfile:1
FROM balenalib/%%BALENA_MACHINE_NAME%%-ubuntu:focal
RUN apt update && apt upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt install -y ca-certificates sudo apt-utils net-tools
COPY nm-mgmt-config-v0.1.1-arm64.deb /
RUN dpkg -i nm-mgmt-config-v0.1.1-arm64.deb
RUN chmod u+x /usr/local/bin/nm-mgmt-config.sh
CMD ["/usr/local/bin/nm-mgmt-config.sh"] 
