title = "nm-exp-active-netrics"
description = "Configuration file for NetMicroscope - Netrics active measurements"
topic = "{TOPIC}"

deployment_json_url = "https://chicago-cdac.github.io/nm-exp-active-netrics/conf/netrics.json"
# Uncomment to set a particular deployment, leave it unset and netrics will choose a 
# deployment randomly 

#deployment = "74e655581a038ce4b7b8a939b17f7cce"

# Meta.Extended info. The infomartion provided here is injected directly into the output json "as is".
# Check nm-mgmt-cms generate_pillar function for more info on how the content of these paramneters
# are being generated.

[extended]
gitlog = "{GITLOG}"
dataver = "{DATAVER}"
debhash = "{DEBHASH}"

[cron]
netrics="""
*/5 * * * * netrics env USER=$LOGNAME /usr/local/bin/netrics -p -d -t -b {enable_ndev} {no_ipquery} {upload} >>{log} 2>&1 
{SPEEDTEST_TIME} {speedtest_hour} * * * netrics env USER=$LOGNAME /usr/local/bin/netrics -s -l {limit-consumption} {no_ipquery} {upload} >>{log} 2>&1 
{IPERF_TIME} {iperf_hour} * * * netrics env USER=$LOGNAME /usr/local/bin/netrics -i {limit-consumption} {no_ipquery} {upload} >{log} 2>&1
0 0 1 * * netrics env USER=$LOGNAME /usr/local/bin/netrics -R >>{log} 2>&1
"""

[databases]
    tinydb_enable = true
    tinydb_path = "databases/"

[reference_site_dict]
    "www.google.com" = "google"
    "www.amazon.com" = "amazon"
    "www.wikipedia.org" = "wikipedia"
    "www.youtube.com" = "youtube"
    "www.facebook.com" = "facebook"
    "www.chicagotribune.com" = "tribune"
    "chicago.suntimes.com" = "suntimes"
    "cs.uchicago.edu" = "uchicago"
    "4.71.251.129" = "Chicago"
    "4.35.238.193" = "Washington_DC"
    "4.71.254.129" = "Atlanta"
    "4.34.58.1" = "Denver"
    "38.102.0.65" = "Seattle"
    "183.178.65.1" = "Hong_Kong"
    "175.45.79.73" = "Sydney"
    "196.24.45.129" = "Johannesburg"
    "41.231.21.1" = "Tunis"
    "77.67.119.129" = "Paris"
    "195.89.146.193" = "Stockholm"
    "190.98.158.1" = "Sao_Paulo"

[limit_consumption]
    measured_down = 5
    max_monthly_consumption_gb = '{max_monthly_consumption_gb}'
    max_monthly_tests = '{max_monthly_tests}'

[latency_under_load]
    targets = ["www.google.com"]

[iperf]
    #buffer_length = 10000
    targets = ["{iperf_host}:{IPERF_PORT}"]

[dns_latency]
    target = "8.8.8.8"

[hops_to_target]
    targets = ["www.google.com"]

[nmap_dev_scan]
    iface = "eth0"

[last_mile_latency]
    "1.1.1.1" = "Cloudflare_DNS"

[oplat]
    targets = ["abbott.cs.uchicago.edu:33317"]

[ookla]
    timeout = 80

[httping]
    c = 2
    targets = ["www.google.com","www.wikipedia.org"]