title = "nm-exp-active-netrics"
description = "Configuration file for NetMicroscope - Netrics active measurements"
topic = "testing"

deployment_json_url = "https://chicago-cdac.github.io/nm-exp-active-netrics/conf/netrics.json"
# Uncomment to set a particular deployment, leave it unset and netrics will choose a 
# deployment randomly 

#deployment = "74e655581a038ce4b7b8a939b17f7cce"

# Meta.Extended info. The infomartion provided here is injected directly into the output json "as is".
# Check nm-mgmt-cms generate_pillar function for more info on how the content of these paramneters
# are being generated.

[extended]
gitlog = "updating speedtest version to speedtest_1.2.0.84-1.ea6b6773cf_arm64"
dataver = "1"
debhash = "9609d1609830a849f53903ae7cc31611a7baee63"

[cron]
netrics="""
*/5 * * * * netrics env USER=$LOGNAME /usr/local/bin/netrics -p -d -t -b -n {upload} >>{log} 2>&1 
1 * * * * netrics env USER=$LOGNAME /usr/local/bin/netrics -s -l --limit-consumption {upload} >>{log} 2>&1 
31 * * * * netrics env USER=$LOGNAME /usr/local/bin/netrics -i --limit-consumption {upload} >{log} 2>&1
0 0 1 * * netrics env USER=$LOGNAME /usr/local/bin/netrics -R >>{log} 2>&1
"""

[databases]
    tinydb_enable = true
    tinydb_path = "databases/"

[reference_site_dict]
    "www.google.com" = "google"
    "www.amazon.com" = "amazon"
    "www.wikipedia.org" = "wikipedia"
    "www.youtube.com" = "youtube"
    "www.facebook.com" = "facebook"
    "www.chicagotribune.com" = "tribune"
    "chicago.suntimes.com" = "suntimes"
    "cs.uchicago.edu" = "uchicago"
    "4.71.251.129" = "Chicago"
    "4.35.238.193" = "Washington_DC"
    "4.71.254.129" = "Atlanta"
    "4.34.58.1" = "Denver"
    "38.102.0.65" = "Seattle"
    "183.178.65.1" = "Hong_Kong"
    "175.45.79.73" = "Sydney"
    "196.24.45.129" = "Johannesburg"
    "41.231.21.1" = "Tunis"
    "77.67.119.129" = "Paris"
    "195.89.146.193" = "Stockholm"
    "190.98.158.1" = "Sao_Paulo"

[resolver_dict]
    "a.passcloud.xyz" = "passcloud"
    "adblock.doh.mullvad.net" = "mullvad"
    "adfree.usableprivacy.net" = "usableprivacy"
    "anycast.dns.nextdns.io" = "nextdns"
    "anycast.uncensoreddns.org" = "uncensoreddns"
    "chewbacca.meganerd.nl" = "meganerd"
    "dns-doh-no-safe-search.dnsforfamily.com" = "dnsforfamily_safe_search"
    "dns-doh.dnsforfamily.com" = "dnsforfamily"
    "dns-family.adguard.com" = "adguard_family"
    "dns-unfiltered.adguard.com" = "adguard_unfiltered"
    "dns.adguard.com" = "adguard"
    "dns.alidns.com" = "alidns"
    "dns.brahma.world" = "brahma"
    "dns.circl.lu" = "circl"
    "dns.cloudflare.com" = "cloudflare"
    "dns.digitale-gesellschaft.ch" = "digitale_gesellschaft"
    "dns.digitalsize.net" = "digitalsize"
    "dns.dnshome.d" = "dnshome"
    "dns.google" = "google"
    "dns.njal.la" = "njal"
    "dns.quad9.net" = "quad9"
    "dns.switch.ch" = "switch"
    "dns.therifleman.name" = "therifleman"
    "dns.twnic.tw" = "twnic"
    "dns1.ryan-palmer.com" = "ryan_palmer"
    "dns10.quad9.net" = "dns10_quad9"
    "dns11.quad9.ne" = "dns11_quad9"
    "dns12.quad9.net" = "dns12_quad9"
    "dns9.quad9.net" = "dns9_quad9"
    "dnsforge.de" = "dnsforge"
    "dnsnl-noads.alekberg.net" = "dnsnl_noads_alekberg"
    "dnsnl.alekberg.net" = "dnsnl_alekberg"
    "dnsse-noads.alekberg.net" = "dnsse_noads_alekberg"
    "dnsse.alekberg.net" = "dnsse_alekberg"
    "doh-2.seby.io" = "seby"
    "doh-ch.blahdns.com" = "ch_blahdns"
    "doh-de.blahdns.com" = "de_blahdns"
    "doh-fi.blahdns.com" = "fi_blahdns"
    "doh-jp.blahdns.com" = "jp_blahdns"
    "doh.appliedprivacy.net" = "appliedprivacy"
    "doh.bortzmeyer.fr" = "bortzmeyer"
    "doh.chi.ahadns.net" = "ahadns"
    "doh.cleanbrowsing.org" = "cleanbrowsing"
    "doh.crypto.sx" = "crypto"
    "doh.dnscrypt.uk" = "dnscrypt"
    "doh.ffmuc.net" = "ffmuc"
    "doh.in.ahadns.net" = "ahadns_in"
    "doh.la.ahadns.net" = "ahadns_la"
    "doh.libredns.gr" = "libredns"
    "doh.mullvad.net" = "mullvad"
    "doh.nl.ahadns.net" = "ahadns_nl"
    "doh.ny.ahadns.net" = "ahadns_ny"
    "doh.opendns.com" = "cisco"
    "doh.pl.ahadns.net" = "ahadns_pl"
    "doh.pub" = "doh_pub"
    "doh.safesurfer.io" = "safesurfer"
    "doh.sb" = "doh_sb"
    "doh.seby.io" = "seby"
    "doh.tiar.app" = "tiar"
    "doh.tiarap.org" = "tiarap"
    "dohtrial.att.net" = "att"
    "family.cloudflare-dns.com" = "cloudflare_family"
    "family.puredns.org" = "puredns_family"
    "fr1.dnswarden.com" = "dnswarden"
    "freedns.controld.com" = "controld"
    "helios.plan9-dns.com" = "plan9"
    "ibksturm.synology.me" = "ibksturm"
    "ind1.dnswarden.com" = "dnswarden"
    "jp.tiar.app" = "jp_tiar"
    "jp.tiarap.org" = "jp_tiarap"
    "kronos.plan9-dns.com" = "kronos"
    "nextdns-ultralow" = "ultralow"
    "odoh-target-noads-se.alekberg.net" = "odoh_noads_se"
    "odoh-target-noads.alekberg.net" = "odoh_noads_ams"
    "odoh-target-se.alekberg.net" = "odoh_se"
    "odoh-target.alekberg.net" = "odoh_ams"
    "odoh.cloudflare-dns.com" = "odoh_cloudflare"
    "odoh.crypto.sx" = "odoh_crypto"
    "ordns.he.net" = "he"
    "pluton.plan9-dns.com" = "pluton"
    "public.dns.iij.jp" = "iij"
    "puredns.org" = "puredns"
    "security.cloudflare-dns.co" = "cloudflare_security"
    "sg1.dnswarden.com" = "adblock_sg1"
    "unicast.uncensoreddns.org" = "uncensoreddns"
    "us1.dnswarden.com" = "dnswarden_us1"
    "v.dnscrypt.uk" = "v_dnscrypt"

[limit_consumption]
    measured_down = 5
    max_monthly_consumption_gb = '200'
    max_monthly_tests = '200'

[latency_under_load]
    targets = ["www.google.com"]

[iperf]
    #buffer_length = 10000
    targets = ["abbott.cs.uchicago.edu:33301"]

[dns_latency]
    target = "8.8.8.8"
    encrypted_dns_targets = ["freedns.controld.com", "anycast.dns.nextdns.io", "doh.crypto.sx", "us1.dnswarden.com", "unicast.uncensoreddns.org", "security.cloudflare-dns.co", "doh.ffmuc.net", "jp.tiar.app", "dns.therifleman.name", "doh.pub", "dns10.quad9.net", "dns.adguard.com", "a.passcloud.xyz", "doh.mullvad.net", "dns12.quad9.net", "dns-unfiltered.adguard.com", "doh-ch.blahdns.com", "dnsse-noads.alekberg.net", "nextdns-ultralow", "fr1.dnswarden.co", "dns.cloudflare.com", "doh.appliedprivacy.net", "dns.alidns.com", "helios.plan9-dns.com", "us1.dnswarden.com", "dnsse.alekberg.net", "doh-fi.blahdns.com", "dns1.ryan-palmer.com", "doh.cleanbrowsing.org", "dns.digitale-gesellschaft.ch", "dns11.quad9.ne", "sg1.dnswarden.com", "dns.circl.lu", "chewbacca.meganerd.nl", "ordns.he.net", "dns12.quad9.net", "dns11.quad9.net", "anycast.uncensoreddns.org", "doh.libredns.gr", "dns.brahma.world", "dns.switch.ch", "dns-doh-no-safe-search.dnsforfamily.com", "doh.chi.ahadns.net", "ibksturm.synology.me", "kronos.plan9-dns.com", "dns-family.adguard.com", "family.puredns.org", "freedns.controld.com", "dnsforge.de", "doh.cleanbrowsing.org", "dns-doh.dnsforfamily.com", "public.dns.iij.jp", "fr1.dnswarden.com", "family.cloudflare-dns.com", "doh.pl.ahadns.net", "doh.cleanbrowsing.org", "dns.google", "freedns.controld.com", "v.dnscrypt.uk", "doh.dnscrypt.uk", "doh.safesurfer.io", "dnsnl.alekberg.net", "fr1.dnswarden.com", "freedns.controld.com", "dns.digitale-gesellschaft.ch", "doh.la.ahadns.net", "doh.tiar.app", "dns.dnshome.d", "doh.sb", "doh-2.seby.io", "doh.tiarap.org", "dns.twnic.tw", "ind1.dnswarden.com", "doh.ny.ahadns.net", "dns.njal.la", "doh.libredns.gr", "pluton.plan9-dns.com", "dns10.quad9.net", "us1.dnswarden.com", "dnsnl-noads.alekberg.net", "jp.tiarap.org", "doh.opendns.com", "doh.seby.io", "dns.quad9.net", "dns.digitalsize.net", "sg1.dnswarden.com", "ind1.dnswarden.com", "puredns.org", "doh.bortzmeyer.fr", "dns9.quad9.net", "doh.in.ahadns.net", "adfree.usableprivacy.net", "dohtrial.att.net", "doh.nl.ahadns.net", "doh-de.blahdns.com", "doh-jp.blahdns.com", "ind1.dnswarden.com", "adblock.doh.mullvad.net", "freedns.controld.com", "jp.tiarap.org", "ibksturm.synology.me", "odoh-target-noads.alekberg.net", "odoh.cloudflare-dns.com", "odoh-target-se.alekberg.net", "odoh-target-noads-se.alekberg.net", "odoh-target.alekberg.net", "jp.tiar.app", "odoh.crypto.sx", "doh.tiarap.org", "doh.tiar.app"]

[hops_to_target]
    targets = ["www.google.com"]

[nmap_dev_scan]
    iface = "eth0"

[last_mile_latency]
    "1.1.1.1" = "Cloudflare_DNS"

[oplat]
    targets = ["abbott.cs.uchicago.edu:33317"]
