#!/bin/sh
### BEGIN INIT INFO
# Provides:          nm-exp-active-netrics
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: NetMicroscope Netrics Active Experment
# Description:       enable NetMicroscope Netrics Active measurements
### END INIT INFO
NMPATH=/usr/local/src/nm-exp-active-netrics/

mkdir -p /tmp/nm/nm-exp-active-netrics/log/
chown netrics:netrics /tmp/nm/ -R

log=/tmp/nm/nm-exp-active-netrics/log/log.txt

if [ ! -d "${NMPATH}" ];then
   echo "ERROR: Installation of nm-exp-active-netrics in incomplete. Exiting..."
   exit 1
fi

if [ ! -f "/usr/local/bin/netrics" ];then
   echo "ERROR: Binaries of nm-exp-active-netrics are not in PATH. Exiting..."
   exit 1
fi


start_nma() {
    upload=""
    if [ -f /etc/nm-exp-active-netrics/.env ];then
	    upload="-u"
	    echo "INFO: /etc/nm-exp-active-netrics/.env present, using -u (upload flag)"
    fi
    echo "Installing nm-exp-active-netrics in crontab (/etc/cron.d/cron-nm-exp-active-netrics)..."

    if [ -f /etc/cron.d/cron-nm-exp-active-netrics ]; then
	    echo "INFO nm-exp-active-netrics already running (cron.d)."
    else
            /usr/local/bin/netrics -G > /tmp/netrics.initd.out
            GETTIME=$(cat /tmp/netrics.initd.out | grep iperf | awk '{print $2}')
            IPERF_TIME=$(( ${GETTIME} + 1 ))
            SPEEDTEST_TIME=$(( ${IPERF_TIME} + 10 )) 

            echo "*/5 * * * * netrics /usr/local/bin/netrics -p -n -d -t -b ${upload} >>${log} 2>&1" > /etc/cron.d/cron-nm-exp-active-netrics
            echo "${SPEEDTEST_TIME} * * * * netrics /usr/local/bin/netrics -s -l ${upload} >>${log} 2>&1" >> /etc/cron.d/cron-nm-exp-active-netrics
            echo "${IPERF_TIME} * * * * netrics /usr/local/bin/netrics -i ${upload} >${log} 2>&1" >> /etc/cron.d/cron-nm-exp-active-netrics
    fi 
}

stop_nma() {
    echo "Removing nm-exp-active-netrics from crontab (/etc/cron.d/cron-nm-exp-active-netrics)..."
    rm -f /etc/cron.d/cron-nm-exp-active-netrics
}

status_nma() {
    if [ -f /etc/cron.d/cron-nm-exp-active-netrics ]; then
	    echo "Status: Running"
    else
	    echo "Status: Stopped"
    fi
    /usr/local/bin/netrics -C
    /usr/local/bin/netrics -L
}

restart_nma() {
	#backup edited cron
	cachedir=/tmp/
	if [ -f /etc/cron.d/cron-nm-exp-active-netrics ]; then
		if [ -d /tmp/nm/nm-exp-active-netrics/cache/ ]; then
			cachedir=/tmp/nm/nm-exp-active-netrics/cache/
		fi
		mv /etc/cron.d/cron-nm-exp-active-netrics $cachedir
		chown netrics:netrics $cachedir/cron-nm-exp-active-netrics
	fi
	stop_nma;start_nma
}

case "$1" in
  start)
	    start_nma
    ;;
  stop)
	    stop_nma
    ;;
  restart)
	    restart_nma
    ;;
  status)
	    status_nma
    ;;
  *)
    echo "Usage: /etc/init.d/cron-nm-exp-active-netrics {start|stop|restart|status}"
    exit 0
    ;;
esac
exit 0
