#!/bin/sh
### BEGIN INIT INFO
# Provides:          nm-exp-active-netrics
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: NetMicroscope Netrics Active Experment
# Description:       enable NetMicroscope Netrics Active measurements
### END INIT INFO
NMPATH=/usr/local/src/nm-exp-active-netrics/

mkdir -p /tmp/nm/nm-exp-active-netrics/log/

log=/tmp/nm/nm-exp-active-netrics/log/log.txt

if [ ! -d "${NMPATH}" ];then
   echo "ERROR: Installation of nm-exp-active-netrics in incomplete. Exiting..."
   exit 1
fi

if [ ! -f "/usr/local/bin/netrics" ];then
   echo "ERROR: Binaries of nm-exp-active-netrics are not in PATH. Exiting..."
   exit 1
fi


start_nma() {
    upload=""
    if [ -f /etc/nm-exp-active-netrics/.env ];then
	    upload="-u"
	    echo "INFO: /etc/nm-exp-active-netrics/.env present, using -u (upload flag)"
    fi
    echo "Installing nm-exp-active-netrics in crontab (/etc/cron.d/cron-nm-exp-active-netrics)..."
    /usr/local/bin/netrics -G > /tmp/netrics.initd.out
    IPERF_TIME=$(cat /tmp/netrics.initd.out | grep iperf | awk '{print $2}')
    SPEEDTEST_TIME=$(( ${IPERF_TIME} + 10 )) 

    echo "*/5 * * * * root /usr/local/bin/netrics -p -n -d -t -b ${upload} >>${log} 2>&1" > /etc/cron.d/cron-nm-exp-active-netrics
    echo "${SPEEDTEST_TIME} * * * * root /usr/local/bin/netrics -s ${upload} >>${log} 2>&1" >> /etc/cron.d/cron-nm-exp-active-netrics
    echo "${IPERF_TIME} * * * * root /usr/local/bin/netrics -i ${upload} >${log} 2>&1" >> /etc/cron.d/cron-nm-exp-active-netrics
}

stop_nma() {
    echo "Removing nm-exp-active-netrics from crontab (/etc/cron.d/cron-nm-exp-active-netrics)..."
    rm -f /etc/cron.d/cron-nm-exp-active-netrics
}

status_nma() {
    /usr/local/bin/netrics -L
    /usr/local/bin/netrics -C
}

case "$1" in
  start)
	    start_nma
    ;;
  stop)
	    stop_nma
    ;;
  restart)
	    stop_nma;start_nma
    ;;
  status)
	    status_nma
    ;;
  *)
    echo "Usage: /etc/init.d/cron-nm-exp-active-netrics {start|stop|restart|status}"
    exit 0
    ;;
esac
exit 0
