#!/bin/sh
### BEGIN INIT INFO
# Provides:          nm-exp-active-netrics
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: NetMicroscope Netrics Active Experment
# Description:       enable NetMicroscope Netrics Active measurements
### END INIT INFO
NMPATH=/usr/local/src/nm-exp-active-netrics/netrics

if [ ! -f "${NMPATH}" ];then
   echo "ERROR: Installation of nm-exp-active-netrics in incomplete. Exiting..."
   exit 1
fi

if [ ! -f "/usr/bin/netrics" ];then
   echo "ERROR: Binaries of nm-exp-active-netrics are not in PATH. Exiting..."
   exit 1
fi

/*
if [ ! -f "${NMPATH}/.env" ];then
   echo "ERROR: ${NMPATH}/.env does not exist. Make sure you have nm-mgmt-* packages installed.Exiting..."
   exit 1
fi

source ${NMPATH}/.env

if [[ ! -z "${NM_EXP_ACTIVE_NETRICS_TARGET_SERVERS}" ]]; then
  echo "ERROR: NM_EXP_ACTIVE_NETRICS_TARGET_SERVERS not set in ${NMPATH}/.env. Exiting..."
  exit 1
fi
*/

case "$1" in
  start)
    echo "Installing nm-exp-active-netrics in crontab (/etc/cron.d/cron-nm-exp-active-netrics)..."
    /usr/bin/netrics -G > /tmp/netrics.initd.out
    IPERF_TIME=$(cat /tmp/netrics.initd.out | grep iperf | awk '{print 2}')

    cat << "EOF" | tee /etc/cron.d/cron-nm-exp-active-netrics > /dev/null
    */5 * * * * python3 /usr/bin/cron-nm-exp-active-netrics -p -n -d -t -b -u 
    1 * * * * python3 /usr/bin/cron-nm-exp-active-netrics -s -u
    ${IPERF_TIME} * * * * python3 /usr/bin/cron-nm-exp-active-netrics -i -u
    EOF

    ;;
  stop)
    echo "Removing nm-exp-active-netrics from crontab (/etc/cron.d/cron-nm-exp-active-netrics)..."
    rm -f /etc/cron.d/cron-nm-exp-active-netrics
    ;;
  status)
    echo "TODO:tail log for errors, count pending, archive etc"
    ;;
  *)
    echo "Usage: /etc/init.d/cron-nm-exp-active-netrics {start|stop|status}"
    exit 0
    ;;
esac
exit 0
