#!/bin/bash

echo "INFO: creating user netrics"

if id "netrics" &>/dev/null; then
    echo 'INFO: user [netrics] found.'
else
    echo 'INFO: user [netrics] not found. Creating...'
    addgroup --system netrics
    adduser --system --home /home/netrics --disabled-password --disabled-login --ingroup netrics netrics
fi

usermod -a -G wireshark netrics

echo "INFO: Please enable non-root users to run tshark wireshark. Eg.:"
echo "INFO: \"$ yes | DEBIAN_FRONTEND=teletype dpkg-reconfigure wireshark-common\""

if [ -f /etc/nm-exp-active-netrics/.env ];then
  chown netrics:netrics /etc/nm-exp-active-netrics/.env
fi


if [ -d /tmp/nm/ ];then
  chown netrics:netrics /tmp/nm/ -R
fi
if [ -f /etc/nm-exp-active-netrics/.env ];then
	chown netrics:netrics /etc/nm-exp-active-netrics/.env
fi
chown netrics:netrics /usr/local/src/nm-exp-active-netrics/ -R
if [ -d /tmp/nm ]; then
	mv /tmp/nm /tmp/nm.backup.$(date +"%Y%m%d")
fi
chmod +x /etc/init.d/nm-exp-active-netrics
update-rc.d nm-exp-active-netrics defaults
/etc/init.d/nm-exp-active-netrics restart
/usr/local/bin/netrics -C
