#!/bin/bash

echo "INFO: creating user netrics"

if id "netrics" &>/dev/null; then
    echo 'INFO: user [netrics] found.'
else
    echo 'INFO: user [netrics] not found. Creating...'
    addgroup --system netrics
    adduser --system --home /home/netrics --disabled-password --disabled-login --ingroup netrics netrics
fi

usermod -a -G wireshark netrics

echo "INFO: Please enable non-root users to run tshark wireshark. Eg.:"
echo "INFO: \"$ yes | DEBIAN_FRONTEND=teletype dpkg-reconfigure wireshark-common\""

### uncomment here to stash archive/pending
## if [ -d /var/nm/ ];then
##	mv /var/nm /var/nm.backup.$(date +"%Y%m%d")
## fi

mkdir -p /var/nm/

if [ -f /etc/nm-exp-active-netrics/.env.netrics ];then
	chown netrics:netrics /etc/nm-exp-active-netrics/.env.netrics
fi

chown netrics:netrics /usr/local/src/nm-exp-active-netrics/ -R
chmod +x /etc/init.d/nm-exp-active-netrics
update-rc.d nm-exp-active-netrics defaults
/etc/init.d/nm-exp-active-netrics restart
chown netrics:netrics /var/nm/ -R
/usr/local/bin/netrics -C

chmod +x /usr/bin/dumpcap
